export default {
    FETCH_DATA : "FETCH_DATA",
    UPDATE_INPUT_DATA : "UPDATE_INPUT_DATA",
    UPDATE_CHECKBOX_DATA : "UPDATE_CHECKBOX_DATA",
    UPDATE_STEP : "UPDATE_STEP",
    SUBMIT_DATA : "SUBMIT_DATA",
    FORM_DATA : "FORM_DATA",
    STEP : "STEP"
}